product_index:
    path:     /
    defaults: { _controller: "ShopBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "ShopBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "ShopBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShopBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShopBundle:Product:delete" }
    methods:  DELETE

product_changeShow:
    path:     /{id}/changeShow
    defaults: { _controller: "ShopBundle:Product:changeShow" }
